#!/bin/bash

INPUT_DATA=$(</dev/stdin)
SAVE_DATA_TO=data/autotune.json

echo "Saving autotune data to $SAVE_DATA_TO"
mkdir -p 'dirname $SAVE_DATA_TO'
echo "$INPUT_DATA" > $SAVE_DATA_TO

npm install

gulp deploy
